name: Blogger Auto Publish

on:
  schedule:
    # 10:00 AM Asia/Kolkata on Mon/Wed/Fri (IST is UTC+5:30)
    - cron: "30 4 * * 1,3,5"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      BLOG_ID: ${{ secrets.BLOG_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      PUBLISH_IMMEDIATELY: "true"
      BLOG_TIMEZONE: "Asia/Kolkata"
      MASTER_PROMPT: ${{ vars.MASTER_PROMPT || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
          date

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # requests used by bot.py
          pip install requests

      - name: Run bot
        run: |
          python bot.py


