name: Auto Blogger Post

on:
  schedule:
    - cron: '0 10 * * 1'  # Monday 10:00 AM UTC
    - cron: '0 10 * * 3'  # Wednesday 10:00 AM UTC
    - cron: '0 10 * * 5'  # Friday 10:00 AM UTC
  workflow_dispatch:  # allows manual trigger

jobs:
  post-blog:
    runs-on: ubuntu-latest

    env:
      BLOG_ID: ${{ secrets.BLOG_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests openai==0.28

      - name: Run blog_post.py
        run: python blog_post.py

