name: Blogger Auto Post

# Schedule: Monday, Wednesday, Friday at 10:00 AM (UTC)
on:
  schedule:
    - cron: '0 10 * * 1'  # Monday 10:00 UTC
    - cron: '0 10 * * 3'  # Wednesday 10:00 UTC
    - cron: '0 10 * * 5'  # Friday 10:00 UTC
  workflow_dispatch:  # Allows manual run from Actions tab

jobs:
  post_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Blogger Bot
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          python blog_post.py
