name: Auto Blogger Post

on:
  schedule:
    # Runs every Monday, Wednesday, and Friday at 10:00 AM UTC
    - cron: "0 10 * * 1,3,5"
  workflow_dispatch: # lets you run manually too

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run blog script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python blog_post.py
